name: Build 281 Vision Orange Pi Image

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - uses: pguyot/arm-runner-action@HEAD
      id: install_deps
      with:
        image_additional_mb: 1500
        bind_mount_repository: true
        base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5.img.xz
        commands: |
          chmod +x install.sh
          ./install.sh

    - name: Compress built image
      run: |
        mv ${{ steps.install_deps.outputs.image }} 281_vision_ubuntu24.04.img
        sudo xz -T 0 -v 281_vision_ubuntu24.04.img

    - uses: actions/upload-artifact@v4.3.4
      with:
        name: 281_vision_ubuntu24.04.img.xz
        path: 281_vision_ubuntu24.04.img.xz
        if-no-files-found: error
        retention-days: 1


